### ISSUE TITLE
0.4.1 not working in studio for me

### ISSUE THREAD

**Issue by apklein** [cg2121/obs-advanced-timer#4]
i dont know if im doing something wrong, or just doesnt work on my obs 25.0.8 (64bits).

**Comment by Janzert** [comment]
I also had this problem and found that the problem seems to be having "Duplicate Sources" selected. When duplicate sources is enabled it seems to grab the value when the scene is transitioned to and then it never gets updated. Disabling it allows the timer to work correctly.

I assume this is probably because obs is copying the text field to a new name internally when duplicating sources.

**Comment by cg2121** [comment]
Make sure not to have duplicate sources checked.
